api:
  host: "0.0.0.0"
  port: "8081"
  path: "/api/v1/*"

until:
  successful:
    maxretries: "3"
    timebetween: "5000"

#rom-salesforce-sys-api
request:
  host: "rom-salesforce-sys-api.us-e2.cloudhub.io"
  port: ""
  path: "/api/v1/"   