api:
  host: "0.0.0.0"
  port: "8083"
  path: "/api/v1/*"

until:
  successful:
    maxretries: "3"
    timebetween: "5000"
    
#rom-salesforce-sys-api
request:
  host: "localhost"
  port: "8081"
  path: "/api/v1/"
  
#salesforce-sys basic authentication and enforcement client_id
reqsalesforce:
  user: "romel"
  client_id: "1371a7d77dd747f3bba037fce27ed889"